---
- hosts: all
  become: yes
  tasks:
    - name: update packages
      apt:
        name: "{{ java }}"
        update_cache: yes
        state: present
      when: ansible_os_family == "Debian"
    - name: installing java
      package:
        name: "{{ java }}"
        state: present
      when: ansible_os_family == "CentoS"
      debug:
        msg: installing java on "{{ ansible_os_family }}"
    - name: tomcat8 installing
      package:
        name: tomcat8
        state: present
      debug:
        msg: installing tomcat8 on "{{ ansible_os_family }}"
        notfiy:
        - restart service
    - name: 
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ tomcat_packages }}"
      debug:
        msg: installing packages on  "{{ ansible_os_family }}"
    - name:
      templete:
        src: templates/tomcat-users.xml.j2
        dest: /var/lib/tomcat8/conf/tomcat-users.xml
    - name: copy war file into tomcat
	  copy:
	    src: /home/ansible/game/*.war
		dest: /var/lib/tomcat8/webapps
      debug:
        msg: copying warfile to  "{{ ansible_os_family }}"
      notfiy:
        - restart service
  
  
  handlers:
  - name: restart service
    service:
      name: tomcat8
      state: restart
  debug:
    msg: service restarting "{{ ansible_os_family }}"
